### ISSUE TITLE
As a administrator I would like to be able to send announcement across movements

### ISSUE THREAD

**Issue by AntoninThioux** [GridtNetwork/gridtlib#22]
A desired feature of the Gridt app is for user administrators to be able to send movement-wide announcements to all users subscribed to this movement. This functionality should be reflected in GridtLib, as these messages should be stored in the connected database.

**Comment by AntoninThioux** [comment]
Hey @Yori-O92, I have a few questions about this user story.
1. Are you in favor of calling them (movement) announcements for clarity? Instead of messages?
2. Should announcements be available to the user based on a time? For example, the message expires after 1 day? 
3. Are we only saving the latest announcement or are we saving all the history of announcements for a movement?
5. Is the plan to be able to upload pictures to the announcements in the future?

We can always change the way announcements are implemented in the future but the more I know now the less will need to be changed in the future :P

**Comment by Yori-O92** [comment]
Hi Antonin,

Good questions!
1. Yes, announcements is a very good term for this;
2  &  3: Ideally, I would make it so that the announcements remain available indefinitely, and a timeline of announcements is created. If this is complicated, we can also make it so that new announcements replace old announcements, but remain available. (If a user joins a movement just after an announcement was made, they should also be able to see what was just announced. So I think it is simplest to just have them remain.)
4. Yes, pictures would be very nice in a future implementation, when we arrive at that stage.

Best,
Yori
